# Generated by Django 5.2.16 on 2026-07-28 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("og_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "og_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("schema_org", models.JSONField(blank=True, null=True)),
                ("robots_noindex", models.BooleanField(default=False)),
                ("robots_nofollow", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL Slug"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/icons/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/images/",
                        verbose_name="Изображение баннера",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="categories__slug_dd870f_idx"
                    )
                ],
            },
        ),
    ]
