# Generated by Django 5.2.16 on 2026-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Описание (EN)"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.TextField(blank=True, verbose_name="Описание (RU)"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_uz",
            field=models.TextField(blank=True, verbose_name="Описание (UZ)"),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_en",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_ru",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description_uz",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title_en",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title_ru",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title_uz",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название (EN)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название (RU)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название (UZ)"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание (Основное)"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Название категории (Основное)"
            ),
        ),
    ]
