# Generated by Django 5.2.16 on 2026-07-28 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_product_description_en_product_description_ru_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvantageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Преимущество (RU)"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Преимущество (UZ)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Преимущество (EN)"
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание (RU)"
                    ),
                ),
                (
                    "subtitle_uz",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание (UZ)"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание (EN)"
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Lucide/FontAwesome Icon key",
                        max_length=100,
                        verbose_name="Имя иконки",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Преимущество магазина",
                "verbose_name_plural": "Преимущества магазина",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_ru",
                    models.CharField(max_length=500, verbose_name="Вопрос (RU)"),
                ),
                (
                    "question_uz",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Вопрос (UZ)"
                    ),
                ),
                (
                    "question_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Вопрос (EN)"
                    ),
                ),
                ("answer_ru", models.TextField(verbose_name="Ответ (RU)")),
                ("answer_uz", models.TextField(blank=True, verbose_name="Ответ (UZ)")),
                ("answer_en", models.TextField(blank=True, verbose_name="Ответ (EN)")),
                (
                    "category_name",
                    models.CharField(
                        default="Общие вопросы",
                        max_length=100,
                        verbose_name="Категория вопроса",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос-Ответ (FAQ)",
                "verbose_name_plural": "Вопросы-Ответы (FAQ)",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок (RU)"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок (UZ)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок (EN)"
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подзаголовок (RU)"
                    ),
                ),
                (
                    "subtitle_uz",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подзаголовок (UZ)"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подзаголовок (EN)"
                    ),
                ),
                (
                    "desktop_image",
                    models.ImageField(
                        upload_to="cms/hero/", verbose_name="Баннер для ПК"
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms/hero/",
                        verbose_name="Баннер для мобильных",
                    ),
                ),
                (
                    "button_text_ru",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст кнопки (RU)"
                    ),
                ),
                (
                    "button_text_uz",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст кнопки (UZ)"
                    ),
                ),
                (
                    "button_text_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст кнопки (EN)"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        default="#",
                        max_length=500,
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        default="#000000", max_length=30, verbose_name="Цвет фона (HEX)"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Приоритет/Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд главного баннера",
                "verbose_name_plural": "Слайды главного баннера",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomeSectionLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Slider"),
                            ("categories", "Категории"),
                            ("popular", "Популярные товары"),
                            ("tradein", "Блок Trade-In"),
                            ("discount", "Товары со скидкой / Акции"),
                            ("collections", "Пользовательские подборки"),
                            ("advantages", "Преимущества магазина"),
                            ("news", "Новости и статьи"),
                            ("partners", "Партнеры и Бренды"),
                            ("faq", "Часто задаваемые вопросы (FAQ)"),
                            ("footer", "Футер и Контакты"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Ключ секции",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок блока (RU)"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок блока (UZ)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок блока (EN)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок вывода"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Отображать блок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Порядок секций главной страницы",
                "verbose_name_plural": "Порядок секций главной страницы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_title_ru",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_title_uz",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_title_en",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_ru",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_uz",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_en",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("og_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "og_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("schema_org", models.JSONField(blank=True, null=True)),
                ("robots_noindex", models.BooleanField(default=False)),
                ("robots_nofollow", models.BooleanField(default=False)),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок (UZ)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок (EN)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "summary_ru",
                    models.TextField(blank=True, verbose_name="Краткое описание (RU)"),
                ),
                (
                    "summary_uz",
                    models.TextField(blank=True, verbose_name="Краткое описание (UZ)"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="Краткое описание (EN)"),
                ),
                ("content_ru", models.TextField(verbose_name="Полный текст (RU)")),
                (
                    "content_uz",
                    models.TextField(blank=True, verbose_name="Полный текст (UZ)"),
                ),
                (
                    "content_en",
                    models.TextField(blank=True, verbose_name="Полный текст (EN)"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="cms/news/", verbose_name="Обложка новости"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(db_index=True, verbose_name="Дата публикации"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Опубликовано"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость / Статья",
                "verbose_name_plural": "Новости и статьи",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_title_ru",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_title_uz",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_title_en",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_ru",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_uz",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_en",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("og_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "og_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("schema_org", models.JSONField(blank=True, null=True)),
                ("robots_noindex", models.BooleanField(default=False)),
                ("robots_nofollow", models.BooleanField(default=False)),
                (
                    "site_name",
                    models.CharField(
                        default="BAHO MARKET",
                        max_length=255,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms/site/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms/site/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        default="+998 71 200 00 00",
                        max_length=50,
                        verbose_name="Основной телефон",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Доп. телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@baho.uz",
                        max_length=254,
                        verbose_name="Email support",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Ташкент, Узбекистан",
                        max_length=255,
                        verbose_name="Физический адрес",
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Ссылка Google Maps",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="Пн-Вс: 09:00 - 21:00",
                        max_length=255,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, default="", verbose_name="Telegram"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, default="", verbose_name="Instagram"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, default="", verbose_name="Facebook"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, default="", verbose_name="YouTube"),
                ),
                (
                    "tiktok_url",
                    models.URLField(blank=True, default="", verbose_name="TikTok"),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="ProductCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_title_ru",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_title_uz",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_title_en",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_ru",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_uz",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "meta_description_en",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("og_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "og_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("schema_org", models.JSONField(blank=True, null=True)),
                ("robots_noindex", models.BooleanField(default=False)),
                ("robots_nofollow", models.BooleanField(default=False)),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, verbose_name="Название подборки (RU)"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название подборки (UZ)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название подборки (EN)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cms/collections/",
                        verbose_name="Баннер подборки",
                    ),
                ),
                (
                    "is_featured_on_home",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Выводить на главной"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collections",
                        to="products.product",
                        verbose_name="Товары подборки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подборка товаров",
                "verbose_name_plural": "Подборки товаров",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
