# Generated by Django 5.2.16 on 2026-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homesectionlayout",
            name="order",
            field=models.PositiveIntegerField(
                default=0, unique=True, verbose_name="Порядок вывода"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL Slug"
            ),
        ),
        migrations.AlterField(
            model_name="productcollection",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL Slug"
            ),
        ),
    ]
