# Generated by Django 5.2.16 on 2026-07-28 14:17

import apps.orders.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        default=apps.orders.models.generate_order_number,
                        max_length=50,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Имя и Фамилия клиента"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("COURIER", "Курьерская доставка"),
                            ("PICKUP", "Самовывоз"),
                        ],
                        default="COURIER",
                        max_length=20,
                        verbose_name="Способ доставки",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="Адрес доставки")),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий к заказу"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Наличными при получении"),
                            ("CARD_UPON_RECEIPT", "Картой при получении"),
                            ("CLICK", "Click"),
                            ("PAYME", "Payme"),
                        ],
                        default="CASH",
                        max_length=30,
                        verbose_name="Способ оплаты",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Итоговая сумма",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("PROCESSING", "В обработке"),
                            ("CONFIRMED", "Подтвержден"),
                            ("SHIPPED", "В пути"),
                            ("DELIVERED", "Доставлен"),
                            ("CANCELLED", "Отменен"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("PROCESSING", "В обработке"),
                            ("CONFIRMED", "Подтвержден"),
                            ("SHIPPED", "В пути"),
                            ("DELIVERED", "Доставлен"),
                            ("CANCELLED", "Отменен"),
                        ],
                        max_length=20,
                        verbose_name="Старый статус",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("PROCESSING", "В обработке"),
                            ("CONFIRMED", "Подтвержден"),
                            ("SHIPPED", "В пути"),
                            ("DELIVERED", "Доставлен"),
                            ("CANCELLED", "Отменен"),
                        ],
                        max_length=20,
                        verbose_name="Новый статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Причина / Комментарий"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "История заказа",
                "verbose_name_plural": "История заказов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, verbose_name="Название товара (снапшот)"
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Цвет (снапшот)"
                    ),
                ),
                (
                    "memory_capacity",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Память (снапшот)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена за unit"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в заказе",
                "verbose_name_plural": "Товары в заказах",
            },
        ),
    ]
