# Generated by Django 5.2.16 on 2026-07-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_idempotency_key"),
        ("products", "0009_productvariant_is_active_productvariant_old_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sim_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="SIM (снапшот)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sku_snapshot",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="SKU (снапшот)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productvariant",
                verbose_name="Вариант SKU",
            ),
        ),
    ]
