# Generated by Django 5.2.16 on 2026-07-28 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="admin",
                max_length=150,
                unique=True,
                verbose_name="Имя пользователя (Логин)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+998901234567'.",
                        regex="^\\+998\\d{9}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
