# Generated by Django 5.2.16 on 2026-07-28 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_product_description_en_product_description_ru_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="compared_in",
                        to="products.product",
                        verbose_name="Товары в сравнении",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение товаров",
                "verbose_name_plural": "Списки сравнения",
            },
        ),
        migrations.CreateModel(
            name="StockNotificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email для уведомления"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Телефон для уведомления",
                    ),
                ),
                (
                    "is_notified",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Уведомлен"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_subscribers",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос уведомления о поступлении",
                "verbose_name_plural": "Запросы уведомлений о поступлении",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentlyViewedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_views",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_viewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Недавно просмотренный товар",
                "verbose_name_plural": "История просмотров товаров",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "product"),
                        name="unique_user_recent_product",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("session_key", "product"),
                        name="unique_session_recent_product",
                    ),
                ],
            },
        ),
    ]
