# Generated by Django 5.2.16 on 2026-07-28 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
        ("products", "0002_product_description_en_product_description_ru_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productcomparison",
            index=models.Index(
                fields=["user", "created_at"], name="interaction_user_id_7e88f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomparison",
            index=models.Index(
                fields=["session_key", "created_at"],
                name="interaction_session_043d74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["user", "created_at"], name="interaction_user_id_03090c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["session_key", "created_at"],
                name="interaction_session_57d8f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocknotificationrequest",
            index=models.Index(
                fields=["product", "is_notified"], name="interaction_product_ac1da0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocknotificationrequest",
            index=models.Index(
                fields=["user", "created_at"], name="interaction_user_id_8f94dc_idx"
            ),
        ),
    ]
