# Generated by Django 5.2.16 on 2026-07-28 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearchQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "query",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Поисковый запрос",
                    ),
                ),
                (
                    "search_count",
                    models.PositiveIntegerField(
                        db_index=True, default=1, verbose_name="Количество поисков"
                    ),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Последнее кол-во результатов"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Закрепить в рекомендуемых",
                    ),
                ),
            ],
            options={
                "verbose_name": "Популярный запрос",
                "verbose_name_plural": "Популярные запросы",
                "ordering": ["-is_pinned", "-search_count"],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "query",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Запрос"
                    ),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кол-во результатов"
                    ),
                ),
                (
                    "clicked_product_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Кликнутый товар ID"
                    ),
                ),
                (
                    "converted_order",
                    models.BooleanField(
                        default=False, verbose_name="Конверсия в заказ"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User Agent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика поиска",
                "verbose_name_plural": "Аналитика поиска",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchSynonym",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_term",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Исходный термин / Синоним",
                    ),
                ),
                (
                    "target_terms",
                    models.CharField(
                        help_text="Заменяемые ключевые слова через запятую",
                        max_length=255,
                        verbose_name="Целевые термины",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Синоним поиска",
                "verbose_name_plural": "Словарь синонимов",
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Сессия гостя",
                    ),
                ),
                (
                    "query",
                    models.CharField(max_length=255, verbose_name="Текст запроса"),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Найдено товаров"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "История поиска",
                "verbose_name_plural": "История поиска",
                "ordering": ["-created_at"],
            },
        ),
    ]
