# Generated by Django 5.2.16 on 2026-07-28 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("og_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "og_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("schema_org", models.JSONField(blank=True, null=True)),
                ("robots_noindex", models.BooleanField(default=False)),
                ("robots_nofollow", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название бренда"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание бренда"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Страна бренда"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["name"],
            },
        ),
    ]
