# Generated by Django 5.2.16 on 2026-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Описание (EN)"),
        ),
        migrations.AddField(
            model_name="brand",
            name="description_ru",
            field=models.TextField(blank=True, verbose_name="Описание (RU)"),
        ),
        migrations.AddField(
            model_name="brand",
            name="description_uz",
            field=models.TextField(blank=True, verbose_name="Описание (UZ)"),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_description_en",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_description_ru",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_description_uz",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_title_en",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_title_ru",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="brand",
            name="meta_title_uz",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
    ]
