# Generated by Django 5.2.16 on 2026-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Полное описание (EN)"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(blank=True, verbose_name="Полное описание (RU)"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(blank=True, verbose_name="Полное описание (UZ)"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_en",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_ru",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description_uz",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title_en",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title_ru",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title_uz",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Название (EN)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Название (RU)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Название (UZ)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_en",
            field=models.TextField(blank=True, verbose_name="Краткое описание (EN)"),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_ru",
            field=models.TextField(blank=True, verbose_name="Краткое описание (RU)"),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description_uz",
            field=models.TextField(blank=True, verbose_name="Краткое описание (UZ)"),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="name_en",
            field=models.CharField(blank=True, max_length=50, verbose_name="Цвет (EN)"),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="name_ru",
            field=models.CharField(blank=True, max_length=50, verbose_name="Цвет (RU)"),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="name_uz",
            field=models.CharField(blank=True, max_length=50, verbose_name="Цвет (UZ)"),
        ),
        migrations.AddField(
            model_name="productmemoryvariant",
            name="capacity_en",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Память (EN)"
            ),
        ),
        migrations.AddField(
            model_name="productmemoryvariant",
            name="capacity_ru",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Память (RU)"
            ),
        ),
        migrations.AddField(
            model_name="productmemoryvariant",
            name="capacity_uz",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Память (UZ)"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Характеристика (EN)"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Характеристика (RU)"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="name_uz",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Характеристика (UZ)"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="value_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Значение (EN)"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="value_ru",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Значение (RU)"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="value_uz",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Значение (UZ)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="Полное описание (Основное)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название товара (Основное)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, verbose_name="Краткое описание (Основное)"
            ),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Цвет (Основное)"),
        ),
        migrations.AlterField(
            model_name="productmemoryvariant",
            name="capacity",
            field=models.CharField(max_length=50, verbose_name="Объем памяти"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Характеристика"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="value",
            field=models.CharField(max_length=255, verbose_name="Значение"),
        ),
    ]
