# Generated by Django 5.2.16 on 2026-07-29 14:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_description_en_product_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="installment_12m_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Если не заполнено, будет рассчитано автоматически",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Рассрочка на 12 мес. (цена в месяц)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="installment_3m_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Если не заполнено, будет рассчитано автоматически",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Рассрочка на 3 мес. (цена в месяц)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="installment_6m_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Если не заполнено, будет рассчитано автоматически",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Рассрочка на 6 мес. (цена в месяц)",
            ),
        ),
    ]
