# Generated by Django 5.2.16 on 2026-07-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_installment_12m_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Канонический URL (Canonical URL)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="Meta Description (Основной)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="Meta Description (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="Meta Description (RU)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description_uz",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="Meta Description (UZ)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=70,
                verbose_name="Meta Title (Основной)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title_en",
            field=models.CharField(
                blank=True, default="", max_length=70, verbose_name="Meta Title (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title_ru",
            field=models.CharField(
                blank=True, default="", max_length=70, verbose_name="Meta Title (RU)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title_uz",
            field=models.CharField(
                blank=True, default="", max_length=70, verbose_name="Meta Title (UZ)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=160,
                verbose_name="OpenGraph Описание (og:description)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=70,
                verbose_name="OpenGraph Заголовок (og:title)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="robots_nofollow",
            field=models.BooleanField(
                default=False, verbose_name="Запретить переход по ссылкам (nofollow)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="robots_noindex",
            field=models.BooleanField(
                default=False, verbose_name="Запретить индексацию (noindex)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="schema_org",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Данные Schema.org (JSON)"
            ),
        ),
    ]
