# Generated by Django 5.2.16 on 2026-07-30 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_canonical_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="battery_health",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Опционально. Заполняется для б/у или уцененных смартфонов/гаджетов (например, 85, 92, 100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Состояние АКБ / Аккумулятора (%)",
            ),
        ),
    ]
