# Generated by Django 5.2.16 on 2026-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_battery_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оставьте пустым, если цена совпадает с базовой",
                max_digits=12,
                null=True,
                verbose_name="Цена для этого цвета (если отличается)",
            ),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Остаток данного цвета"
            ),
        ),
    ]
