# Generated by Django 5.2.16 on 2026-07-30 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productcolor_price_override_productcolor_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSimVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sim_type",
                    models.CharField(
                        choices=[
                            ("esim", "eSIM (Только электронная SIM)"),
                            ("dual_esim", "Dual SIM (Physical Nano-SIM + eSIM)"),
                            (
                                "dual_physical",
                                "Dual Physical SIM (2 Физические nano-SIM, HK/China)",
                            ),
                            ("single_sim", "Single SIM (1 Физическая SIM)"),
                        ],
                        default="dual_esim",
                        max_length=30,
                        verbose_name="Тип SIM-карты",
                    ),
                ),
                (
                    "name_override",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Свое название конфигурации (опционально)",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Оставьте пустым, если цена совпадает с базовой",
                        max_digits=12,
                        null=True,
                        verbose_name="Индивидуальная цена для этой SIM-версии",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Остаток данной SIM-версии"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sim_variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант SIM-карты",
                "verbose_name_plural": "Варианты SIM-карт",
            },
        ),
    ]
