# Generated by Django 5.2.16 on 2026-07-30 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productsimvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Точная цена при выборе этой комбинации памяти, SIM и цвета",
                        max_digits=12,
                        verbose_name="Итоговая цена этой комбинации (сум)",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Остаток данной конкретной комбинации"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Уникальный SKU вариации",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sku_variants",
                        to="products.productcolor",
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sku_variants",
                        to="products.productmemoryvariant",
                        verbose_name="Память",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
                (
                    "sim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sku_variants",
                        to="products.productsimvariant",
                        verbose_name="SIM-карта",
                    ),
                ),
            ],
            options={
                "verbose_name": "⚡ Точная комбинация товара (Память + SIM + Цвет)",
                "verbose_name_plural": "⚡ Точные комбинации цен и остатков (Matrix Pricing)",
            },
        ),
    ]
