# Generated by Django 5.2.16 on 2026-07-30 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Старая цена (для скидки)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Точная цена при выборе этой комбинации памяти, SIM и цвета",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Итоговая цена этой комбинации (сум)",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "memory", "sim", "color"),
                name="unique_product_memory_sim_color_combination",
            ),
        ),
    ]
