# Generated by Django 5.2.16 on 2026-07-30 11:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productvariant_is_active_productvariant_old_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="installment_12m_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оставьте пустым для авторасчета от цены этой комбинации",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Рассрочка 12 мес (в мес)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="installment_3m_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оставьте пустым для авторасчета от цены этой комбинации",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Рассрочка 3 мес (в мес)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="installment_6m_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оставьте пустым для авторасчета от цены этой комбинации",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Рассрочка 6 мес (в мес)",
            ),
        ),
    ]
