# Generated by Django 5.2.16 on 2026-07-30 13:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productvariant_installment_12m_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Базовая цена",
            ),
        ),
    ]
