# Generated by Django 5.2.16 on 2026-07-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/colors/",
                verbose_name="Изображение товара этого цвета",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_images",
                to="products.productcolor",
                verbose_name="Привязать к цвету (опционально)",
            ),
        ),
    ]
