# Generated by Django 5.2.16 on 2026-07-28 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "months",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Срок в месяцах"
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Процент наценки (например: 15.00 для 15%)",
                        max_digits=5,
                        verbose_name="Процент наценки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тариф рассрочки",
                "verbose_name_plural": "Тарифы рассрочки",
                "ordering": ["months"],
            },
        ),
        migrations.CreateModel(
            name="TradeInRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Модель устройства (например: iPhone 13 Pro)",
                    ),
                ),
                (
                    "memory_capacity",
                    models.CharField(
                        max_length=50, verbose_name="Объем памяти (например: 128 ГБ)"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("LIKE_NEW", "Как новый (без царапин)"),
                            ("GOOD", "Хорошее (микроцарапины)"),
                            ("FAIR", "Удовлетворительное (следы использования)"),
                            ("POOR", "Плохое (трещины, дефекты)"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание дефектов / комплектации"
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="IMEI (необязательно)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tradein/",
                        verbose_name="Фото устройства",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=150, verbose_name="Имя клиента"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
            ],
            options={
                "verbose_name": "Заявка Trade-In",
                "verbose_name_plural": "Заявки Trade-In",
                "ordering": ["-created_at"],
            },
        ),
    ]
